### ISSUE TITLE
Error Pulling Image s2i-minimal-notebook

### ISSUE THREAD

**Issue by dymurray** [jupyter-on-openshift/jupyterhub-quickstart#11]
```
[dymurray@dymurray-desktop sbcli]$ oc get is                          
NAME                      DOCKER REPO                                     TAGS      UPDATED                                                 
jupyterhub                172.30.1.1:5000/dylan/jupyterhub                latest    21 minutes ago                                          
s2i-minimal-notebook      172.30.1.1:5000/dylan/s2i-minimal-notebook      3.5       26 minutes ago                                          
s2i-scipy-notebook        172.30.1.1:5000/dylan/s2i-scipy-notebook        3.5       23 minutes ago                                          
s2i-tensorflow-notebook   172.30.1.1:5000/dylan/s2i-tensorflow-notebook 
```

```
$ oc describe pod jupyterhub-nb-272442c5-2de4d4-2d40fd-2d8054-2dfcc1349e9c42
  FirstSeen     LastSeen        Count   From                    SubObjectPath                   Type            Reason          Message
  ---------     --------        -----   ----                    -------------                   --------        ------          -------
  11s           11s             1       default-scheduler                                       Normal          Scheduled       Successfully assigned jupyterhub-nb-272442c5-2de4d4-2d40fd-2d8054-2dfcc1349e9c42 to localhost
  10s           10s             1       kubelet, localhost      spec.containers{notebook}       Normal          Pulling         pulling image "s2i-minimal-notebook:3.5"
  5s            5s              1       kubelet, localhost      spec.containers{notebook}       Warning         Failed          Failed to pull image "s2i-minimal-notebook:3.5": rpc error: code = Unknown desc = repository docker.io/s2i-minimal-notebook not found: does not exist or no pull access
  5s            5s              1       kubelet, localhost      spec.containers{notebook}       Warning         Failed          Error: ErrImagePull
  4s            4s              1       kubelet, localhost      spec.containers{notebook}       Normal          BackOff         Back-off pulling image "s2i-minimal-notebook:3.5"
  4s            4s              1       kubelet, localhost      spec.containers{notebook}       Warning         Failed          Error: ImagePullBackOff
```

Any idea why I am seeing this?

**Comment by dymurray** [comment]
Just to clarify... the jupyterhub-nb pod is created when I do "start server". This is what fails. I don't get why the `jupyterhub` imagestream isn't failing to be pulled but the minimal-notebook is.

**Comment by GrahamDumpleton** [comment]
What OpenShift instance are you using?

The problem is that the OpenShift instance is missing a default configuration for what is called the ImagePolicy plugin and so that plugin is not enabled as it should be. The configuration should be present, but if the cluster was upgraded from an older OpenShift version it may be missing. If using recent Minishift it is also missing because adding it was removed from ``oc cluster up`` and Minishift didn't compensate and add it back.

For Minishift you can see a discussion about it in:

* https://github.com/minishift/minishift/issues/2392

For Minishift you can fix the issue by running:

```
minishift openshift config set --patch '{"admissionConfig": {"pluginConfig": {"openshift.io/ImagePolicy": {"configuration": {"resolutionRules": null, "kind": "ImagePolicyConfig", "executionRules": [{"skipOnResolutionFailure": true, "invertMatch": false, "name": "execution-denied", "onResources": [{"resource": "pods", "group": ""}, {"resource": "builds", "group": ""}], "matchRegistries": null, "matchIntegratedRegistry": false, "matchImageLabels": null, "matchImageAnnotations": [{"set": false, "value": "true", "key": "images.openshift.io/deny-execution"}], "ignoreNamespaceOverride": false, "reject": true, "matchDockerImageLabels": null}], "apiVersion": "v1", "resolveImages": ""}, "location": ""}}}}'
```

If you are on a full OpenShift installation, then the  master config file for the cluster needs to be updated to add the appropriate ImagePolicy plugin configuration. I am not sure what services need to be restarted after that.

As per:

* https://github.com/minishift/minishift/issues/2379

the ImagePolicy plugin configuration needs to look something like:

```
admissionConfig:
  pluginConfig:
    GenericAdmissionWebhook:
      configuration:
        apiVersion: v1
        disable: false
        kind: DefaultAdmissionConfig
      location: ""
    openshift.io/ImagePolicy:
      configuration:
        apiVersion: v1
        executionRules:
        - ignoreNamespaceOverride: false
          invertMatch: false
          matchDockerImageLabels: null
          matchImageAnnotations:
          - key: images.openshift.io/deny-execution
            set: false
            value: "true"
          matchImageLabels: null
          matchIntegratedRegistry: false
          matchRegistries: null
          name: execution-denied
          onResources:
          - group: ""
            resource: pods
          - group: ""
            resource: builds
          reject: true
          skipOnResolutionFailure: true
        kind: ImagePolicyConfig
        resolutionRules: null
        resolveImages: ""
      location: ""
```

This is taken from another Minishift issue, but should be same for a full OpenShift cluster.

As a temporary workaround until you can resolve the issue, you can change:

```
s2i-minimal-notebook
```

in the template parameter to be:

```
172.30.1.1:5000/dylan/s2i-minimal-notebook
```

That is, reference it from the internal image registry explicitly.
